import fs from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';

const BASE=(process.env.SRIS_STAGING_URL||'https://sris-pilot-v1-staging.up.railway.app').replace(/\/$/,'');
const CUSTOM=(process.env.SRIS_CUSTOM_URL||'https://app.sris.io').replace(/\/$/,'');
const EXPECTED=process.env.SRIS_EXPECTED_BUILD||'20260905-demo-measured-mission-v38';
const OUT=process.env.QA_OUTPUT_DIR||'qa-current-live-public';
fs.mkdirSync(OUT,{recursive:true});
const report={started_at:new Date().toISOString(),base:BASE,custom:CUSTOM,expected:EXPECTED,checks:[],findings:[],pages:{},requests:[]};
const rank={critical:0,major:1,minor:2,info:3};
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
function finding(severity,area,title,detail='',evidence={}){report.findings.push({severity,area,title,detail,evidence});}
function check(name,ok,detail='',severity='major',evidence={}){report.checks.push({name,ok:!!ok,detail,severity,evidence});if(!ok)finding(severity,'check',name,detail,evidence);return !!ok;}
async function http(url){const started=Date.now();const r=await fetch(url,{redirect:'manual'});const body=await r.text();return{status:r.status,headers:Object.fromEntries(r.headers.entries()),body,ms:Date.now()-started};}
function security(label,item){const h=item.headers;check(`${label}: CSP`,!!h['content-security-policy'],JSON.stringify(h),'major');check(`${label}: HSTS`,!!h['strict-transport-security'],JSON.stringify(h),'major');check(`${label}: nosniff`,h['x-content-type-options']==='nosniff',JSON.stringify(h),'major');check(`${label}: frame denied`,h['x-frame-options']==='DENY',JSON.stringify(h),'major');check(`${label}: referrer policy`,!!h['referrer-policy'],JSON.stringify(h),'minor');check(`${label}: permissions policy`,!!h['permissions-policy'],JSON.stringify(h),'minor');}
async function axe(page,name){try{const r=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();report.pages[name].axe=r.violations.map(v=>({id:v.id,impact:v.impact,help:v.help,nodes:v.nodes.length,targets:v.nodes.slice(0,5).map(n=>n.target)}));for(const v of r.violations){finding(['critical','serious'].includes(v.impact)?'major':'minor','accessibility',`${name}: ${v.id}`,`${v.help}; nodes=${v.nodes.length}`,{impact:v.impact,targets:v.nodes.slice(0,5).map(n=>n.target)})}}catch(e){finding('major','accessibility',`${name}: axe scan failed`,String(e?.stack||e));}}
async function overflow(page,name){const x=await page.evaluate(()=>({clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,offenders:[...document.querySelectorAll('body *')].filter(el=>{const r=el.getBoundingClientRect();return r.right>document.documentElement.clientWidth+2||r.left<-2}).slice(0,20).map(el=>({tag:el.tagName,id:el.id,cls:String(el.className||''),left:Math.round(el.getBoundingClientRect().left),right:Math.round(el.getBoundingClientRect().right)}))}));report.pages[name].overflow=x;check(`${name}: no page-level horizontal overflow`,x.scrollWidth<=x.clientWidth+2,JSON.stringify(x),'major');}
function wire(page,name){report.pages[name]={console:[],errors:[],failed:[]};page.on('console',m=>{const x={type:m.type(),text:m.text(),url:m.location()?.url||''};report.pages[name].console.push(x);if(m.type()==='error'&&!/401/.test(x.text))finding('major','browser-console',`${name}: console error`,x.text,x)});page.on('pageerror',e=>{report.pages[name].errors.push(String(e?.stack||e));finding('critical','browser-runtime',`${name}: uncaught page error`,String(e?.stack||e))});page.on('requestfailed',r=>{const x={method:r.method(),url:r.url(),error:r.failure()?.errorText||''};report.pages[name].failed.push(x);if(!/ERR_ABORTED/.test(x.error))finding('major','browser-network',`${name}: request failed`,`${x.method} ${x.url} ${x.error}`,x)});page.on('response',r=>{if(r.url().startsWith(BASE)||r.url().startsWith(CUSTOM)){report.requests.push({page:name,url:r.url(),method:r.request().method(),status:r.status()});if(r.status()>=500)finding('critical','http',`${name}: HTTP ${r.status()}`,r.url())}});}
async function shot(page,name){await page.screenshot({path:path.join(OUT,`${name}.png`),fullPage:true});}

let fatal=null;
try{
  for(const origin of [BASE,CUSTOM]){
    for(const route of ['/','/app','/account.html','/demonstracao','/health','/api/pilot/capabilities','/api/pilot/build']){
      const x=await http(`${origin}${route}`);report.pages[`http:${origin}${route}`]=x;check(`${origin}${route}: HTTP 200`,x.status===200,`status=${x.status}`,'critical');security(`${origin}${route}`,x);if(route!='/health')check(`${origin}${route}: build header`,x.headers['x-sris-pilot-build']===EXPECTED,`actual=${x.headers['x-sris-pilot-build']||''}`,'critical');check(`${origin}${route}: under 3s`,x.ms<3000,`${x.ms}ms`,'major');
    }
  }
  const openapi=await http(`${BASE}/openapi.json`);report.pages['http:openapi']=openapi;check('Managed staging does not publish OpenAPI schema',openapi.status===404,`status=${openapi.status}`,'major');
  const release=await http(`${BASE}/api/pilot/release-state`);report.pages['http:release-state']=release;check('Release-state requires authentication',[401,403].includes(release.status),`status=${release.status}`,'critical');
  const profile=await http(`${BASE}/api/pilot/profile`);check('Profile requires authentication',[401,403].includes(profile.status),`status=${profile.status}`,'critical');
  const caps=JSON.parse((await http(`${BASE}/api/pilot/capabilities`)).body);report.capabilities=caps;check('Runtime build expected',caps.build===EXPECTED,JSON.stringify(caps),'critical');check('Five user moments exactly',JSON.stringify(caps.user_moments)===JSON.stringify(['context','evidence','decision','measurement','memory']),JSON.stringify(caps.user_moments),'critical');check('Eight canonical records exactly',JSON.stringify(caps.canonical_records)===JSON.stringify(['observation','evidence','hypothesis','alternative','decision','action','outcome','learning']),JSON.stringify(caps.canonical_records),'critical');check('Live Business Case advertised',caps.live_business_case===true,JSON.stringify(caps),'critical');check('Workspace selection advertised',caps.explicit_workspace_selection===true,JSON.stringify(caps),'critical');check('Transactional email ready',caps.transactional_email_ready===true,JSON.stringify(caps),'critical');check('Password reset delivered by email',caps.password_reset_delivery==='email',JSON.stringify(caps),'critical');check('Invitations enabled',caps.invitations_enabled===true,JSON.stringify(caps),'critical');check('Public signup disabled for controlled pilot',caps.public_signup===false,JSON.stringify(caps),'major');

  const browser=await chromium.launch({headless:true});
  try{
    const ctx=await browser.newContext({viewport:{width:1440,height:1000},locale:'pt-PT'});const p=await ctx.newPage();wire(p,'home-desktop');
    await p.goto(`${BASE}/`,{waitUntil:'networkidle',timeout:45000});await shot(p,'01-home-desktop');check('Login form visible',await p.locator('#login-form').isVisible(),'', 'critical');check('Hero image visible',await p.locator('.auth-photo').isVisible(),'', 'major');const imgs=await p.locator('img').evaluateAll(xs=>xs.map(x=>({src:x.currentSrc,complete:x.complete,w:x.naturalWidth,h:x.naturalHeight,alt:x.alt})));report.pages['home-desktop'].images=imgs;check('All entry images load',imgs.every(x=>x.complete&&x.w>0),JSON.stringify(imgs),'critical');
    const reg=await p.locator('#register-tab').evaluate(el=>({disabled:el.disabled,visible:!!(el.offsetWidth||el.offsetHeight||el.getClientRects().length),title:el.title}));report.pages['home-desktop'].register=reg;check('Create-account control remains visible',reg.visible,JSON.stringify(reg),'major');check('Create-account disabled consistently with controlled signup',reg.disabled===true,JSON.stringify(reg),'major');const subtitle=clean(await p.locator('#auth-subtitle').innerText().catch(()=>''));if(reg.disabled&&/crie uma conta|criar conta/i.test(subtitle))finding('major','ux-consistency','Entry copy promises account creation while control is disabled',subtitle,{register:reg});
    await p.fill('#login-email','definitely-not-an-account@example.com');await p.fill('#login-password','Definitely-Wrong-Password-123!');const lrP=p.waitForResponse(r=>r.url().includes('/api/auth/login'),{timeout:15000});await p.click('#login-submit');const lr=await lrP;check('Invalid login is rejected',lr.status()===401,`status=${lr.status()}`,'critical');await p.waitForTimeout(250);const msg=clean(await p.locator('#message').innerText());check('Invalid-login message human-readable',/incorret|credenc/i.test(msg),msg,'major');
    await p.click('#forgot-link');await p.fill('#reset-email',`unknown-${Date.now()}@example.com`);const rrP=p.waitForResponse(r=>r.url().includes('/api/auth/password-reset/request'),{timeout:15000});await p.click('#reset-request-submit');const rr=await rrP;let rrBody={};try{rrBody=await rr.json()}catch{}report.pages['home-desktop'].unknown_reset={status:rr.status(),body:rrBody};check('Unknown-address reset responds neutrally',rr.status()===202,JSON.stringify(rrBody),'critical');check('Reset response exposes no token',!rrBody.reset_token,JSON.stringify(rrBody),'critical');check('Reset response does not enumerate account',/se .*conta|se existir|caso exista/i.test(clean(rrBody.message)),JSON.stringify(rrBody),'major');await axe(p,'home-desktop');await overflow(p,'home-desktop');

    const ap=await ctx.newPage();wire(ap,'account-desktop');await ap.goto(`${BASE}/account.html`,{waitUntil:'networkidle',timeout:45000});await shot(ap,'02-account-desktop');check('Account recovery surface visible',await ap.locator('#request-view').isVisible(),'', 'critical');check('Recovery submit is enabled when email ready',!(await ap.locator('#request-submit').isDisabled()),'', 'critical');await axe(ap,'account-desktop');await overflow(ap,'account-desktop');

    const dp=await ctx.newPage();wire(dp,'demo-desktop');await dp.goto(`${BASE}/demonstracao`,{waitUntil:'networkidle',timeout:45000});await dp.waitForFunction(()=>{const t=document.querySelector('#mission-title')?.textContent||'';return t&&!/carregar/i.test(t)},null,{timeout:20000});await shot(dp,'03-demo-desktop');const body=clean(await dp.locator('body').innerText());report.pages['demo-desktop'].excerpt=body.slice(0,6000);check('Demo clearly labels fictional data',/dados.*fict[ií]ci/i.test(body),body.slice(0,700),'critical');check('Demo mission loads',!/carregar demonstração/i.test(body),body.slice(0,700),'critical');check('Demo includes Business Case Vivo',/Business Case Vivo/i.test(body),body.slice(0,2500),'critical');check('Demo includes decision matrix',/Matriz de alternativas/i.test(body),body.slice(0,2500),'critical');check('Demo includes evidence graph',/Grafo de evidência/i.test(body),body.slice(0,2500),'critical');const uuid=body.match(/\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b/ig)||[];check('Demo exposes no raw UUIDs',uuid.length===0,JSON.stringify(uuid.slice(0,10)),'major');
    const scenarios=dp.locator('#scenario-controls button');const n=await scenarios.count();check('Demo exposes multiple economic scenarios',n>=2,`count=${n}`,'critical');if(n>=2){const before=clean(await dp.locator('#business-case-timeline').innerText());const active=await scenarios.evaluateAll(xs=>xs.findIndex(x=>x.classList.contains('active')));const target=active===0?1:0;await scenarios.nth(target).click();await dp.waitForTimeout(250);const after=clean(await dp.locator('#business-case-timeline').innerText());check('Scenario switching changes projected output',before!==after,JSON.stringify({active,target,before:before.slice(-700),after:after.slice(-700)}),'critical');}
    const graph=dp.locator('#evidence-graph .graph-node');const gn=await graph.count();check('Evidence graph contains interactive nodes',gn>0,`count=${gn}`,'major');if(gn){await graph.last().click();await dp.waitForTimeout(150);check('Evidence graph click updates detail',clean(await dp.locator('#graph-detail').innerText()).length>20,clean(await dp.locator('#graph-detail').innerText()),'major');}
    await axe(dp,'demo-desktop');await overflow(dp,'demo-desktop');

    const up=await ctx.newPage();wire(up,'app-unauthenticated');await up.goto(`${BASE}/app`,{waitUntil:'domcontentloaded',timeout:45000});await up.waitForTimeout(2500);report.pages['app-unauthenticated'].final=up.url();await shot(up,'04-app-unauthenticated');check('Unauthenticated /app returns to login entry',new URL(up.url()).pathname==='/',up.url(),'critical');await ctx.close();

    const mctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,locale:'pt-PT'});const mp=await mctx.newPage();wire(mp,'home-mobile');await mp.goto(`${BASE}/`,{waitUntil:'networkidle',timeout:45000});await shot(mp,'05-home-mobile');check('Mobile login input visible',await mp.locator('#login-email').isVisible(),'', 'critical');await mp.focus('#login-email');await mp.waitForTimeout(200);const focus=await mp.evaluate(()=>({active:document.activeElement?.id,clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth}));report.pages['home-mobile'].focus=focus;check('Mobile input remains focusable',focus.active==='login-email',JSON.stringify(focus),'major');await axe(mp,'home-mobile');await overflow(mp,'home-mobile');const md=await mctx.newPage();wire(md,'demo-mobile');await md.goto(`${BASE}/demonstracao`,{waitUntil:'networkidle',timeout:45000});await md.waitForFunction(()=>!document.querySelector('#mission-title')?.textContent?.toLowerCase().includes('carregar'),null,{timeout:20000});await shot(md,'06-demo-mobile');await axe(md,'demo-mobile');await overflow(md,'demo-mobile');const scroll=md.locator('.table-scroll');if(await scroll.count()){const metrics=await scroll.evaluate(el=>({client:el.clientWidth,scroll:el.scrollWidth,tabindex:el.getAttribute('tabindex')}));report.pages['demo-mobile'].matrix=metrics;check('Mobile comparison matrix is horizontally usable',metrics.scroll>=metrics.client,JSON.stringify(metrics),'major');}
    await mctx.close();
  } finally {await browser.close();}

  const robots=await http(`${BASE}/robots.txt`);if(robots.status===404)finding('minor','crawler-hygiene','robots.txt is absent on staging',`status=${robots.status}`);
} catch(e){fatal=String(e?.stack||e);finding('critical','runner','Live public QA aborted',fatal);process.exitCode=2;} finally {
  report.completed_at=new Date().toISOString();report.findings.sort((a,b)=>(rank[a.severity]??9)-(rank[b.severity]??9));report.summary={checks:report.checks.length,passed:report.checks.filter(c=>c.ok).length,failed:report.checks.filter(c=>!c.ok).length,critical:report.findings.filter(f=>f.severity==='critical').length,major:report.findings.filter(f=>f.severity==='major').length,minor:report.findings.filter(f=>f.severity==='minor').length};fs.writeFileSync(path.join(OUT,'current-live-public-qa.json'),JSON.stringify(report,null,2));const md=['# SRIS current live public QA','',`Checks: ${report.summary.passed}/${report.summary.checks} passed`,`Findings: ${report.summary.critical} critical · ${report.summary.major} major · ${report.summary.minor} minor`,'','## Findings',...report.findings.map((f,i)=>`${i+1}. **${f.severity.toUpperCase()} · ${f.area} · ${f.title}** — ${clean(f.detail)}`),'','## Failed checks',...report.checks.filter(c=>!c.ok).map((c,i)=>`${i+1}. **${c.severity.toUpperCase()} · ${c.name}** — ${clean(c.detail)}`)].join('\n');fs.writeFileSync(path.join(OUT,'current-live-public-qa.md'),md);console.log('===== SRIS_CURRENT_LIVE_PUBLIC_QA_START =====');console.log(JSON.stringify(report.summary));console.log(md);console.log('===== SRIS_CURRENT_LIVE_PUBLIC_QA_END =====');
}
