const $=(s)=>document.querySelector(s),$$=(s)=>[...document.querySelectorAll(s)];
const token=()=>localStorage.getItem('sris_access_token');
let profile=null,missions=[],selectedMission=null,profileAvailable=false;

function logout(){['sris_access_token','sris_refresh_token','sris_org_id'].forEach(k=>localStorage.removeItem(k));location.href='/';}
function errText(data,status){const d=data?.detail;if(typeof d==='string')return d;if(d?.message)return d.message;if(d?.code)return d.code;return data?.message||`Erro ${status}`;}
async function api(path,options={}){const headers={...(options.headers||{})};if(!(options.body instanceof FormData))headers['Content-Type']='application/json';if(token())headers.Authorization=`Bearer ${token()}`;const res=await fetch(path,{...options,headers});let data={};try{data=await res.json()}catch{}if(res.status===401){logout();throw new Error('Sessão expirada.');}if(!res.ok)throw new Error(errText(data,res.status));return data;}

const titles={overview:'Visão geral',mission:'Mission Intelligence',copilot:'Copiloto IA',billing:'Créditos e planos',account:'Conta'};
function setProviderState(label,state='degraded'){const el=$('#provider-state');if(!el)return;el.textContent=label;el.dataset.state=state;}
function go(section){$$('.section').forEach(s=>s.classList.toggle('active',s.id===section));$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.section===section));$('#page-title').textContent=titles[section]||'SRIS';$('#sidebar').classList.remove('open');if(section==='mission'&&orgId())loadMissions();window.scrollTo({top:0,behavior:'smooth'});}
$$('.nav button').forEach(b=>b.addEventListener('click',()=>go(b.dataset.section)));
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
$('#menu-btn')?.addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
$('#logout-btn')?.addEventListener('click',logout);$('#logout-btn-2')?.addEventListener('click',logout);

function money(v){return Number(v||0).toFixed(2)}
function initials(name){return(name||'S').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function orgId(){return profile?.organization?.id||localStorage.getItem('sris_org_id')}
function miBase(){return `/api/organizations/${encodeURIComponent(orgId())}/mission-intelligence`}

function renderProfile(p){profile=p;profileAvailable=true;const u=p.user||{},o=p.organization||{},ai=p.ai||{};if(o.id)localStorage.setItem('sris_org_id',o.id);$('#mini-name').textContent=u.full_name||u.email||'Utilizador';$('#mini-org').textContent=o.name||'Workspace';$('#avatar').textContent=initials(u.full_name);$('#welcome-title').textContent=`Olá${u.full_name?' '+u.full_name.split(' ')[0]:''}. O que precisa de decidir?`;['#balance-eur','#billing-balance','#copilot-balance'].forEach(s=>{if($(s))$(s).textContent=money(ai.credit_eur)});$('#plan-name').textContent=(ai.plan||'pilot').replace(/^./,x=>x.toUpperCase());$('#model-name').textContent=ai.model||'Não configurado';$('#copilot-model').textContent=ai.model||'IA';$('#copilot-model-2').textContent=ai.model||'Não configurado';$('#requests-used').textContent=ai.requests_used||0;$('#requests-limit').textContent=ai.request_limit||0;$('#workspace-role').textContent=(o.role||'Membro').toUpperCase();$('#workspace-name').textContent=o.name||'Workspace individual';$('#account-name').value=u.full_name||'';$('#account-email').value=u.email||'';$('#account-org').value=o.name||'';$('#account-role').value=o.role||'';const ready=ai.provider_configured&&ai.runtime_enabled;$('#ai-status').textContent=ready?'Disponível':'Ainda não ativa';setProviderState(ready?'IA operacional':'IA não ativa',ready?'ready':'degraded');renderLedger(ai.ledger||[]);}
function renderDegradedProfile(){profileAvailable=false;setProviderState('Ligação parcial','degraded');$('#ai-status').textContent='A sincronizar';$('#model-name').textContent='Estado indisponível';$('#workspace-role').textContent='—';$('#workspace-name').textContent=orgId()?'Workspace identificado':'Workspace por sincronizar';['#balance-eur','#billing-balance','#copilot-balance'].forEach(s=>{if($(s))$(s).textContent='0.00'});}
function renderLedger(rows){const el=$('#ledger');if(!el)return;if(!rows.length){el.innerHTML='<div class="note">Ainda não existem movimentos.</div>';return;}el.innerHTML=rows.map(r=>{const amount=Number(r.amount_eur||0),label=r.kind==='trial'?'Crédito inicial':r.kind==='test_topup'?'Crédito de teste':r.kind==='ai_usage'?'Utilização de IA':r.kind;return `<div class="ledger-row"><span><strong>${label}</strong><div class="note">${r.reference||''}</div></span><strong>${amount>0?'+':''}${amount.toFixed(4)} €</strong></div>`}).join('');}
async function refresh(){const data=await api('/api/pilot/profile');renderProfile(data);return data;}

async function askAI(message,context,answerEl,button){answerEl.classList.remove('empty');answerEl.textContent='A analisar…';button?.classList.add('loading');try{const data=await api('/api/pilot/ai/ask',{method:'POST',body:JSON.stringify({message,context:context||null})});answerEl.textContent=data.answer;$('#last-charge').textContent=`${Number(data.charged_eur||0).toFixed(4)} €`;try{await refresh()}catch{}return data;}catch(err){answerEl.textContent=`Não foi possível concluir a análise: ${err.message}`;answerEl.classList.add('empty');throw err;}finally{button?.classList.remove('loading');}}
$('#copilot-form')?.addEventListener('submit',async e=>{e.preventDefault();try{await askAI($('#copilot-message').value.trim(),$('#copilot-context').value.trim(),$('#copilot-answer'),e.submitter);}catch{}});

function installCopilotActions(){const form=$('#copilot-form');if(!form||$('#copilot-quick-actions'))return;const wrap=document.createElement('div');wrap.id='copilot-quick-actions';wrap.className='button-row';wrap.style.margin='0 0 16px';[['Pontos cegos','Identifica os três pontos cegos mais importantes nesta decisão e explica o impacto potencial de cada um.'],['Contradições','Procura contradições, pressupostos frágeis e informação que possa alterar materialmente esta decisão.'],['Evidência em falta','Indica a evidência que falta obter, ordenada pelo valor que pode ter para a decisão.'],['Alternativas','Propõe alternativas reais e compara custos, riscos, reversibilidade e informação necessária.']].forEach(([label,prompt])=>{const b=document.createElement('button');b.type='button';b.className='btn btn-secondary compact';b.textContent=label;b.addEventListener('click',()=>{$('#copilot-message').value=prompt;$('#copilot-message').focus();});wrap.appendChild(b);});form.parentNode.insertBefore(wrap,form);}

function showMissionMode(mode){$('#mission-empty').classList.toggle('hidden',mode!=='empty');$('#mission-editor').classList.toggle('hidden',mode!=='editor');$('#mission-detail').classList.toggle('hidden',mode!=='detail');}
function resetMissionForm(parent=null){$('#mission-form').reset();$('#mission-domain').value='cross_domain';$('#mission-kind').value='mission';$('#mission-priority').value='strategic';$('#mission-parent-id').value=parent?.id||'';$('#mission-code-label').textContent=parent?`SUB-MISSÃO DE ${parent.code}`:'NOVA MISSÃO';$('#mission-editor-title').textContent=parent?'Criar sub-missão':'Criar missão';$('#save-mission-btn').textContent=parent?'Criar sub-missão':'Criar missão';$('#cancel-mission-btn').classList.remove('hidden');$('#mission-message').className='alert hidden';showMissionMode('editor');}
$('#new-mission-btn')?.addEventListener('click',()=>resetMissionForm());$('#empty-new-btn')?.addEventListener('click',()=>resetMissionForm());$('#cancel-mission-btn')?.addEventListener('click',()=>selectedMission?openMission(selectedMission.id):showMissionMode('empty'));$('#create-submission-btn')?.addEventListener('click',()=>selectedMission&&resetMissionForm(selectedMission));$('#detail-submission-btn')?.addEventListener('click',()=>selectedMission&&resetMissionForm(selectedMission));
function missionRow(m){const indent=Math.min(Number(m.depth||0),5)*14;return `<button class="mission-item ${selectedMission?.id===m.id?'active':''}" data-mid="${m.id}" style="padding-left:${14+indent}px"><span><strong>${m.title}</strong><small>${m.code} · ${m.mission_kind==='program'?'Programa':'Missão'}${m.children_count?` · ${m.children_count} sub`:''}</small></span><span class="mission-state">${m.lifecycle_state||'active'}</span></button>`;}
function renderMissionList(){const q=$('#mission-search').value.trim().toLowerCase();const rows=missions.filter(m=>!q||`${m.title} ${m.code}`.toLowerCase().includes(q));$('#mission-list').innerHTML=rows.length?rows.map(missionRow).join(''):'<div class="note">Nenhuma missão encontrada.</div>';$$('[data-mid]').forEach(b=>b.addEventListener('click',()=>openMission(b.dataset.mid)));}
$('#mission-search')?.addEventListener('input',renderMissionList);
async function loadMissions(){if(!orgId()){showMissionMode('empty');$('#mission-list').innerHTML='<div class="note">O workspace ainda está a sincronizar.</div>';return;}$('#mission-list').innerHTML='<div class="note">A sincronizar missões…</div>';try{missions=await api(`${miBase()}/missions`);renderMissionList();if(!selectedMission)showMissionMode('empty');}catch(err){$('#mission-list').innerHTML=`<div class="alert error">Não foi possível sincronizar as missões.<br><button class="btn btn-secondary compact" id="retry-missions" style="margin-top:10px">Tentar novamente</button></div>`;$('#retry-missions')?.addEventListener('click',loadMissions);}}
async function openMission(id){try{const m=await api(`${miBase()}/missions/${encodeURIComponent(id)}`);selectedMission=m;renderMissionList();$('#detail-code').textContent=m.path_codes?.join(' / ')||m.code;$('#detail-title').textContent=m.title;$('#detail-objective').textContent=m.objective||'Ainda não definido';$('#detail-question').textContent=m.central_question||'Ainda não definida';$('#detail-context').textContent=m.context||'Ainda não existe contexto registado.';$('#detail-meta').innerHTML=`<span>${m.mission_kind==='program'?'Programa':'Missão'}</span><span>${m.priority||'strategic'}</span><span>Rev. ${m.revision}</span><span>${m.lifecycle_state||'active'}</span>`;$('#mission-answer').textContent='Escolha “Analisar com IA” quando quiser produzir uma nova leitura analítica desta missão.';$('#mission-answer').classList.add('empty');showMissionMode('detail');loadAttachments();loadHistory();}catch(err){$('#mission-list').insertAdjacentHTML('afterbegin',`<div class="alert error">Não foi possível abrir esta missão.</div>`);}}
$('#mission-form')?.addEventListener('submit',async e=>{e.preventDefault();const box=$('#mission-message'),payload={title:$('#mission-title').value.trim(),objective:$('#mission-objective').value.trim(),context:$('#mission-context').value.trim(),central_question:$('#mission-question').value.trim(),parent_mission_id:$('#mission-parent-id').value||null,mission_kind:$('#mission-kind').value,domain:$('#mission-domain').value.trim()||'cross_domain',priority:$('#mission-priority').value,horizon:$('#mission-horizon').value.trim(),stakeholders:[]};e.submitter?.classList.add('loading');try{const m=await api(`${miBase()}/missions`,{method:'POST',body:JSON.stringify(payload)});box.textContent='Missão criada e guardada.';box.className='alert success';await loadMissions();await openMission(m.id);}catch(err){box.textContent=err.message;box.className='alert error';}finally{e.submitter?.classList.remove('loading');}});
$('#detail-analyze-btn')?.addEventListener('click',async e=>{if(!selectedMission)return;const prompt=`Analisa esta missão persistente do SRIS. Distingue rigorosamente factos, hipóteses, lacunas de evidência, riscos, alternativas e próximos passos.\n\nMissão: ${selectedMission.code} — ${selectedMission.title}\nObjetivo: ${selectedMission.objective}\nPergunta central: ${selectedMission.central_question}`;try{await askAI(prompt,selectedMission.context,$('#mission-answer'),e.currentTarget);}catch{}});
$$('[data-mission-tab]').forEach(b=>b.addEventListener('click',()=>{$$('[data-mission-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('.mission-tab').forEach(x=>x.classList.toggle('active',x.id===`mission-tab-${b.dataset.missionTab}`));}));
async function loadAttachments(){if(!selectedMission)return;try{const rows=await api(`${miBase()}/missions/${encodeURIComponent(selectedMission.code)}/attachments`);$('#attachment-list').innerHTML=rows.length?rows.map(a=>`<div class="attachment-row"><span><strong>${a.original_filename||a.filename||'Documento'}</strong><small>${a.extraction_status||'registado'}${a.byte_size?` · ${Math.ceil(a.byte_size/1024)} KB`:''}</small></span><span class="pill">${a.extension||'file'}</span></div>`).join(''):'<div class="note">Sem documentos carregados.</div>';}catch(err){$('#attachment-list').innerHTML='<div class="note">Os documentos desta missão não estão disponíveis neste momento.</div>';}}
$('#upload-file-btn')?.addEventListener('click',async e=>{if(!selectedMission)return;const file=$('#mission-file').files[0];if(!file){alert('Selecione primeiro um documento.');return;}const fd=new FormData();fd.append('file',file);e.currentTarget.classList.add('loading');try{await api(`${miBase()}/missions/${encodeURIComponent(selectedMission.code)}/attachments`,{method:'POST',body:fd});$('#mission-file').value='';await loadAttachments();}catch(err){alert(`Não foi possível carregar o documento: ${err.message}`);}finally{e.currentTarget.classList.remove('loading');}});
async function loadHistory(){if(!selectedMission)return;try{const rows=await api(`${miBase()}/dialogues?mission_code=${encodeURIComponent(selectedMission.code)}`);$('#dialogue-history').innerHTML=rows.length?rows.map(d=>`<div class="timeline-row"><span class="timeline-dot"></span><div><strong>${d.status||'Sessão analítica'}</strong><div class="note">${d.created_at?new Date(d.created_at).toLocaleString('pt-PT'):''}</div></div></div>`).join(''):'<div class="note">Ainda não existem sessões interativas nesta missão.</div>';}catch{$('#dialogue-history').innerHTML='<div class="note">Histórico temporariamente indisponível.</div>';}}

$$('.topup').forEach(b=>b.addEventListener('click',async()=>{const box=$('#billing-message');box.className='alert hidden';try{const data=await api('/api/pilot/credits/test-topup',{method:'POST',body:JSON.stringify({amount_eur:Number(b.dataset.amount)})});box.textContent=`Crédito de teste adicionado. Novo saldo: ${money(data.credit_eur)} €.`;box.className='alert success';try{await refresh()}catch{}}catch(err){box.textContent=err.message;box.className='alert error';}}));

function refineStaticCopy(){const cap=$('.capability-chips');if(cap)cap.setAttribute('aria-hidden','true');const empty=$('#mission-empty .empty-state p');if(empty)empty.textContent='Crie ou abra uma missão. O contexto, documentos, decisões e aprendizagem permanecem ligados ao trabalho.';const billingNote=$('#billing .card .note');if(billingNote)billingNote.textContent='Crédito de teste do piloto. Não existem pagamentos reais nesta fase.';installCopilotActions();}

(async()=>{if(!token()){location.href='/';return;}refineStaticCopy();try{await refresh();}catch(err){console.warn('Pilot profile unavailable:',err.message);renderDegradedProfile();}if(orgId())loadMissions();try{const plans=await api('/api/pilot/plans');if(plans?.plans?.length){const byCode=Object.fromEntries(plans.plans.map(x=>[x.code,x]));[['professional',1],['organization',2]].forEach(([code,i])=>{const p=byCode[code],el=$$('#plan-grid .price')[i];if(p&&el)el.innerHTML=`${Number(p.monthly_eur).toFixed(0)} €<span style="font-size:14px">/mês</span>`;});}}catch{}setTimeout(()=>{if(!profileAvailable&&orgId())loadMissions();},1500);})();