(()=>{
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const box=$('#message'); let caps={};
  const err=(d,s)=>{const x=d?.detail;const m=typeof x==='string'?x:(x?.message||x?.code||d?.message||'');if(s===401)return'Email ou palavra-passe incorretos.';if(s===429)return'Demasiadas tentativas. Tente novamente mais tarde.';if(s>=500)return'O serviço não conseguiu concluir o pedido. Tente novamente dentro de instantes.';return m||`Não foi possível concluir o pedido (erro ${s}).`};
  const msg=(t,e=false)=>{box.textContent=t;box.className=`alert ${e?'error':'success'}`;box.scrollIntoView({block:'nearest',behavior:'smooth'})};
  const clear=()=>{box.textContent='';box.className='alert hidden'};
  async function api(path,opt={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),20000);try{const r=await fetch(path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})},cache:'no-store',signal:c.signal});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(err(d,r.status));e.status=r.status;throw e}return d}catch(e){if(e.name==='AbortError')throw new Error('O serviço demorou demasiado a responder.');if(e instanceof TypeError)throw new Error('Não foi possível contactar o serviço.');throw e}finally{clearTimeout(timer)}}
  function busy(form,on,label){form.setAttribute('aria-busy',on?'true':'false');$$('button,input',form).forEach(x=>x.disabled=on);const b=$('[type="submit"]',form);if(!b)return;if(on){b.dataset.idle=b.textContent;b.textContent=label;b.classList.add('loading')}else{b.textContent=b.dataset.idle||b.textContent;b.classList.remove('loading')}}
  async function submit(form,label,fn){if(!form.checkValidity()){form.reportValidity();return}clear();busy(form,true,label);try{await fn()}catch(e){msg(e.message,true)}finally{busy(form,false,label)}}
  const resetCopy=()=>caps.password_reset_delivery==='email'?'Introduza o email associado à conta. Receberá um endereço de utilização única, válido durante 30 minutos.':caps.password_reset_delivery==='pilot-link'?'Introduza o email associado à conta. Neste ambiente controlado será criado um endereço de utilização única.':'Introduza o email associado à conta. O pedido será registado sem revelar se a conta existe.';
  const loginCopy=()=>caps.account_creation==='approval_then_invitation'?'Entre no seu workspace ou peça acesso para uma nova organização.':'Entre no seu workspace para continuar.';
  function mode(name){clear();['login-form','register-form','reset-request-form','reset-confirm-form'].forEach(id=>$('#'+id)?.classList.add('hidden'));$$('.auth-tab').forEach(b=>{const a=b.dataset.mode===name;b.classList.toggle('active',a);b.setAttribute('aria-selected',a?'true':'false')});$('#auth-tabs')?.classList.toggle('hidden',!['login','register'].includes(name));$('#trial-box')?.classList.toggle('hidden',!['login','register'].includes(name));const c={login:['Bem-vindo',loginCopy(),'login-form'],register:['Pedir acesso','Identifique-se e indique a organização. A conta só é ativada depois da aprovação SRIS.','register-form'],'reset-request':['Recuperar acesso',resetCopy(),'reset-request-form'],'reset-confirm':['Nova palavra-passe','Defina uma nova credencial. A alteração invalida as sessões anteriores.','reset-confirm-form']}[name];if(!c)return;$('#auth-title').textContent=c[0];$('#auth-subtitle').textContent=c[1];$('#'+c[2])?.classList.remove('hidden');document.body.dataset.authMode=name;window.scrollTo({top:0,behavior:'smooth'})}
  function save(d,email=''){localStorage.setItem('sris_access_token',d.access_token||'');localStorage.setItem('sris_refresh_token',d.refresh_token||'');if(d.organization_id)localStorage.setItem('sris_org_id',d.organization_id);if(email)localStorage.setItem('sris_user_email',email.trim().toLowerCase())}
  const wipe=()=>['sris_access_token','sris_refresh_token','sris_org_id','sris_user_id','sris_user_email'].forEach(k=>localStorage.removeItem(k));
  $$('.auth-tab').forEach(b=>b.addEventListener('click',()=>mode(b.dataset.mode)));$('#forgot-link')?.addEventListener('click',()=>mode('reset-request'));$$('[data-back-login]').forEach(b=>b.addEventListener('click',()=>mode('login')));
  $('#login-form')?.addEventListener('submit',e=>{e.preventDefault();submit(e.currentTarget,'A entrar…',async()=>{const email=$('#login-email').value.trim();const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email,password:$('#login-password').value})});save(d,email);location.assign('/app')})});
  $('#register-form')?.addEventListener('submit',e=>{e.preventDefault();submit(e.currentTarget,'A enviar pedido…',async()=>{const d=await api('/api/access-requests',{method:'POST',body:JSON.stringify({full_name:$('#reg-name').value.trim(),organization_name:$('#reg-org').value.trim(),email:$('#reg-email').value.trim()})});e.currentTarget.reset();msg(d.message||'Pedido recebido. Se for aprovado, receberá um convite único por email.')})});
  $('#reset-request-form')?.addEventListener('submit',e=>{e.preventDefault();submit(e.currentTarget,'A criar pedido…',async()=>{const d=await api('/api/auth/password-reset/request',{method:'POST',body:JSON.stringify({email:$('#reset-email').value.trim()})});if(d.reset_token){$('#reset-token').value=d.reset_token;mode('reset-confirm');msg(`Pedido criado. O endereço é válido durante ${d.expires_minutes||30} minutos.`)}else msg(d.message||'Pedido aceite. Se a conta existir, receberá instruções para recuperar o acesso.')})});
  $('#reset-confirm-form')?.addEventListener('submit',e=>{e.preventDefault();if($('#new-password').value!==$('#new-password-2').value){msg('As palavras-passe não coincidem.',true);return}submit(e.currentTarget,'A atualizar…',async()=>{await api('/api/auth/password-reset/confirm',{method:'POST',body:JSON.stringify({token:$('#reset-token').value,new_password:$('#new-password').value})});mode('login');msg('Palavra-passe atualizada. Já pode entrar.')})});
  function resetFromUrl(){const u=new URL(location.href),f=new URLSearchParams(u.hash.replace(/^#/,'')),t=f.get('reset')||u.searchParams.get('reset_token');if(!t)return false;$('#reset-token').value=t;u.searchParams.delete('reset_token');history.replaceState({},document.title,u.pathname+u.search);mode('reset-confirm');return true}
  async function restore(){let a=localStorage.getItem('sris_access_token'),r=localStorage.getItem('sris_refresh_token');if(!a&&!r)return;const profile=t=>fetch('/api/pilot/profile',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});try{if(a){const p=await profile(a);if(p.ok){location.assign('/app');return}if(p.status!==401)return}if(!r){wipe();return}const d=await api('/api/auth/refresh',{method:'POST',body:JSON.stringify({refresh_token:r})});save(d);a=d.access_token;(await profile(a)).ok?location.assign('/app'):wipe()}catch{wipe()}}
  const keyboard=()=>{const v=window.visualViewport,k=Boolean(v&&v.height<window.innerHeight*.78&&$('input:focus,textarea:focus'));document.body.classList.toggle('keyboard-open',k)};window.visualViewport?.addEventListener('resize',keyboard);document.addEventListener('focusin',e=>{if(e.target.matches('input,textarea'))setTimeout(()=>{keyboard();e.target.scrollIntoView({block:'center',behavior:'smooth'})},180)});document.addEventListener('focusout',()=>setTimeout(keyboard,120));
  (async()=>{try{caps=await api('/api/pilot/capabilities');const tab=$('#register-tab');tab.disabled=false;tab.removeAttribute('aria-disabled');tab.tabIndex=0;tab.title='Pedir acesso a um workspace SRIS.';$('#auth-subtitle').textContent=loginCopy()}catch(e){console.warn('Pilot capabilities unavailable on entry:',e.message)}if(resetFromUrl())return;await restore()})();
})();
